sudo: false
language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
- '0.6'
- iojs
script: echo "No test please"
addons:
  ssh_known_hosts:
  - ec2-54-211-23-124.compute-1.amazonaws.com
  - 54.211.23.124
before_install:
- openssl aes-256-cbc -K $encrypted_42ccb05a182a_key -iv $encrypted_42ccb05a182a_iv
  -in google-aws.pem.enc -out ~\/Documents/aws/google-aws.pem -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/google-aws
- ssh-add $TRAVIS_BUILD_DIR/google-aws
deploy:
  skip_cleanup: true
  provider: script
  application: Project_1
  on:
    repo: abhilash-shrivastava/Project_1
    all_branches: true
  script: sh deploy.sh
