sudo: false
language: node_js

node_js:
  - "node"
script: echo "No test please"
addons:
  ssh_known_hosts:
  - ec2-54-209-196-250.compute-1.amazonaws.com
  - 54.209.196.250
before_install:
- openssl aes-256-cbc -K $encrypted_42ccb05a182a_key -iv $encrypted_42ccb05a182a_iv
  -in google-aws.pem.enc -out google-aws.pem -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/google-aws.pem
- ssh-add $TRAVIS_BUILD_DIR/google-aws.pem
deploy:
  skip_cleanup: true
  provider: script
  application: Project_1
  on:
    repo: abhilash-shrivastava/Project_1
    all_branches: true
  script: sh deploy.sh
